#!/usr/bin/env bash
# Generate the "Local 64k + Office" preset from the working local-64k: the same
# composition, but with the skills catalog (tool-skill) enabled for document
# sessions (.xlsx/.docx/.pptx/.univer), so the model sees the univer skills and
# loads them itself.
# The .mjs modules are not copied - name: ./x.mjs rows are rewritten to
# ../local-64k/x.mjs (a relative specifier).
# Re-run after every change to local-64k/agent.cordis.yml; DSH re-reads the
# presets when the web starts.
set -euo pipefail
SRC="$HOME/.dsh/.agent-presets/local-64k"
DST="$HOME/.dsh/.agent-presets/local-64k-office"
mkdir -p "$DST"
python3 - "$SRC/agent.cordis.yml" "$DST/agent.cordis.yml" <<'PY'
import sys, re
src, dst = sys.argv[1], sys.argv[2]
s = open(src).read()
a = "- id: tool-skill\n  name: '@deepseek-ai/dsh-tool-skill'\n  disabled: true\n"
if s.count(a) != 1: sys.exit("tool-skill row not found in base preset — make-office-preset.sh needs re-targeting")
s = s.replace(a, "- id: tool-skill\n  name: '@deepseek-ai/dsh-tool-skill'\n  # Office variant: the skills catalog (univer) is enabled.\n", 1)
s, n = re.subn(r"(name: )\./", r"\1../local-64k/", s)
head = ("# GENERATED by scripts/make-office-preset.sh from ../local-64k/agent.cordis.yml -\n"
        "# DO NOT EDIT BY HAND; change local-64k and regenerate.\n")
open(dst, "w").write(head + s)
print(f"office preset: {n} module rows → ../local-64k/, tool-skill enabled")
PY
cat > "$DST/preset.yml" <<'YML'
name: Local 64k + Office
description: Same as Local 64k plus the univer skills catalog for documents (.xlsx/.docx/.pptx/.univer). Generated by scripts/make-office-preset.sh - do not edit by hand.
order: 2
YML
echo "→ $DST"
